ctrs:
    hosts:
        10.147.17.200:
          vars:
            type: DVRS
            iden_channel: 3
            voice_channel: 120
            control_channel: 120
            super_group: 911
            wacn: dee00
            rfss: 2
            site: 3C
            nac: 13C
            sys: 13B
            fne_port: 62032
            fne_node: 60001
            modem_port: /dev/ttyAMA0
            fne_identity: 2-3C DVRS
            callsign: WRUP970
            rcon_password: "$8ZPx5hz$pn6z"
            vc_rcon_port: 9991
            vc_rcon_address: 10.147.17.200
            vc_tx_tuning: 0
            vc_rx_tuning: 0
            gmt_offset: -6
            info_lat: 31
            info_long: -98
            info_location: "Texas, USA"
