ctrs:
    hosts:
        10.147.17.27:
          vars:
            type: CONV
            fne_node: 36010
            fne_port: 63030
            fne_identity: 1-24 CONV
            rest_address: 10.147.17.27
            rest_port: 9990
            rest_password: "CalebisGay"
            iden_channel: 3
            control_channel: 120
            voice_channel: 120
            rfss: 1
            site: 24
            nac: 13B
            super_group: 911
            wacn: dee00
            sys: 134
            modem_port: null
            tx_tuning: 0
            rx_tuning: 0
            info_lat: 30.299419
            info_long: -97.691909
            info_location: "Texas"
            gmt_offset: -6
            callsign: WRUP970