ctrs:
    hosts:
        10.147.17.214:
          vars:
            type: VC
            iden_channel: 2
            voice_channel: 624
            control_channel: 624
            super_group: 911
            wacn: dee00
            rfss: 1
            site: 29
            nac: 139
            sys: 13B
            fne_port: 62030
            fne_node_vc: 12002
            modem_port_vc: /dev/ttyAMA0
            fne_identity_vc: 1-29 VC
            callsign: WRUP970
            rcon_password: "ads(LKkjhf67898!"
            vc_rcon_port: 9992
            vc_rcon_address: 10.147.17.214
            vc_tx_tuning: 0
            vc_rx_tuning: 0
            gmt_offset: -6
            info_lat: 31
            info_long: -98
            info_location: "Texas, USA"