ctrs:
    hosts:
        10.147.17.153:
          vars:
            type: CONV
            iden_channel: 3
            voice_channel: 910
            control_channel: 910
            super_group: 911
            wacn: dee00
            rfss: 1
            site: 1
            nac: 131
            sys: 13B
            fne_port: 62030
            fne_node: 1005
            modem_port: /dev/ttyAMA0
            fne_identity: 1-1 BU CONV
            callsign: WRUP970
            rcon_password: "jX2i6WTGCjpu"
            vc_rcon_port: 9991
            vc_rcon_address: 10.147.17.153
            vc_tx_tuning: 0
            vc_rx_tuning: 0
            gmt_offset: -6
            info_lat: 31
            info_long: -98
            info_location: "Texas, USA"