ctrs:
    hosts:
        10.147.17.4:
          vars:
            type: DVRS
            iden_channel: 3
            voice_channel: 122
            control_channel: 122
            super_group: 911
            wacn: dee00
            rfss: 1
            site: 17
            nac: 137
            sys: 13B
            fne_node: 23101
            modem_port: /dev/ttyAMA0
            fne_identity: 1-17 DVRS
            callsign: WRUP970
            rcon_password: "7q0cJXpElZxH"
            vc_rcon_port: 9991
            vc_rcon_address: 10.147.17.4
            vc_tx_tuning: 0
            vc_rx_tuning: 0
            gmt_offset: -6
            info_lat: 31
            info_long: -98
            info_location: "Texas, USA"