ctrs:
    hosts:
        10.147.17.149:
          vars:
            type: VOC
            iden_channel: 3
            voice_channel: 120
            control_channel: 120
            super_group: 911
            wacn: dee00
            rfss: 1
            site: 2D
            nac: 13D
            sys: 13B
            fne_port: 62030
            fne_node: 45001
            modem_port: /dev/ttyAMA0
            fne_identity: 1-2D VOC
            callsign: WRUP970
            rcon_password: "HjN8K8vH6OVx"
            gmt_offset: -6
            info_lat: -83.689428
            info_long: -39.194973
            info_location: "Repeater Site, Antarctica"
            vc_rcon_port: 9991
            vc_rcon_address: 10.147.17.149
            vc_tx_tuning: 0
            vc_rx_tuning: 0